---
- name: install fish
  package:
    name: fish
  when: fish_install_package
  tags:
    - fish

- name: Create fish config dir
  ansible.builtin.file:
    path: "{{ fish_home_path }}/{{ item }}"
    state: directory
    owner: "{{ fish_username }}"
    group: "{{ fish_groupname | default(fish_username) }}"
    mode: "0640"
  loop:
    - .config/fish/
    - .config/fish/conf.d
  tags:
    - fish

- name: Configure friendly interactive shell
  ansible.builtin.template:
    src: templates/config.fish.j2
    dest: "{{ fish_home_path }}/.config/fish/config.fish"
    mode: "0640"
  tags:
    - fish

- name: Configure fish to use local tmux
  ansible.builtin.template:
    src: templates/local_tmux.conf
    dest: "{{ fish_home_path }}/.config/fish/conf.d/local_tmux.fish"
    mode: "0640"
  tags:
    - fish
  when: fish_local_tmux

- name: Configure fish to use tmux for ssh sessions
  ansible.builtin.template:
    src: templates/ssh_tmux.conf
    dest: "{{ fish_home_path }}/.config/fish/conf.d/ssh_tmux.fish"
    mode: "0640"
  tags:
    - fish
  when: fish_local_tmux

- name: Allow fishshell
  become: true
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "{{ fish_exe_path }}"

- name: Change shell of user
  ansible.builtin.user:
    name: "{{ fish_username }}"
    shell: "{{ fish_exe_path }}"
  become: true
  tags:
    - fish
  changed_when: false
